### ISSUE TITLE
This repo is big as fekal

### ISSUE THREAD

**Issue by hroncok** [syky27/LunchGuy#2]
And I consider that bad practice... :(

**Comment by hroncok** [comment]
Cloning into 'lunch_guy-ios'...
remote: Counting objects: 623, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 623 (delta 0), reused 0 (delta 0), pack-reused 619
Receiving objects: 100% (623/623), **32.70 MiB** | 630.00 KiB/s, done.
Resolving deltas: 100% (173/173), done.
Checking connectivity... done.

**Comment by syky27** [comment]
There are used 2 huge frameworks
- Fabric (crash reporting tool)
- Realm (database)

Nothing I can do about it.

**Comment by hroncok** [comment]
Is it necessary to keep it in the repo? Cannot you have some kind of podfile.lock that would tell what libraries to download and use?

**Comment by hroncok** [comment]
Oh wait, you already do and I guessed the name almost right.

**Comment by syky27** [comment]
There are 2 options how manage this, you either have only Podfile, for installing dependencies and you basically don't push those dependencies into repo.

The other way is to push all necessary files for correct compilation to repo, because those third party libs might become unavailable in future.

I went with the second option for obvious reasons.

**Comment by hroncok** [comment]
OK, it's your repo. I still disagree but I respect your reasons.
