### ISSUE TITLE
Guideline 4.2.2 - Design - Minimum Functionality

### ISSUE THREAD

**Issue by syky27** [syky27/LunchGuy#21]
We noticed that your app’s main functionality is to market your service, with limited or no user-facing interactive features or functionality. Apps that are primarily marketing materials or advertisements are not appropriate for the App Store.

Please see attached screenshots for details.

The next submission of this app may require a longer review time.

Next Steps

- Review the Minimum Functionality section of the App Store Review Guidelines.
- Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program. 
- Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.

If you believe your app is compliant with the App Store Review Guidelines, you may submit an appeal. Alternatively, you may provide additional details about your app by replying directly to this message.

**Comment by syky27** [comment]
@josefdolezal lol

**Comment by josefdolezal** [comment]
I think that you can discuss that with them - the guidlines are not violated. Write them that the app is not used to market our services.

**Comment by syky27** [comment]
I know
--
Tomas Sykora

**Comment by syky27** [comment]
Hello, I would like to point out that this app does not market my service.

This app takes, data from local restaurants around CTU (Czech Technical University) campus and shows daily menu.

The map is there only to show where the restaurants are, this is non profit app for me or AJTY. 

Please reconsider, because it really does not violate any guidelines.

Thank you very much.

**Comment by syky27** [comment]
Hello,

Thank you for your reply. However, we noticed that your app’s main functionality is to market a service, with limited or no user-facing interactive features or functionality. 

In order to be considered for the App Store and to avoid any further related rejections, it would be appropriate to make this app compliant with the App Store Review Guideline 4.2.2 - Design - Minimum Functionality.

Request a phone call from App Review

At your request, we can arrange for an Apple Representative to call you within the next three business days to discuss your App Review issue.

To request a call and ensure we have accurate contact information, reply directly to this message with a contact name and direct phone number to reach you.

Best regards,

App Store Review

**Comment by syky27** [comment]
Hello, 

I am still not sure, if you understand. This app does not market any service. It show what you can choose to eat around Czech Technical University campus.

If this app is in violation of guidelines can you explain me why this app: https://itunes.apple.com/bn/app/menzy-cvut/id512233720?mt=8 is not? It does the very same thing, but just with different set of restaurants.

This last build added feature which allows user to see location of restaurants on the map. Can you explain me why have you just suddenly decided that it doesn't meet guidelines? How is it even possible that this app is in AppStore, with lesser functionality than this build that I am trying to get validate?

Thank you for quick response!
Tomas Sykora

**Comment by syky27** [comment]
Hello,

Thank you for your reply. Your app contains limited or no user-facing interactive features or functionality. 

Also, we found that the usefulness of your app is limited by the minimal amount of content or features it includes. 

We encourage you to review your app concept and incorporate different content and features that are in compliance with the App Store Review Guidelines.

We understand that there are no hard and fast rules to define useful or entertaining, but Apple and Apple customers expect apps to provide a really great user experience. Apps should provide valuable utility or entertainment, draw people in by offering compelling capabilities or content, or enable people to do something they couldn't do before or in a way they couldn't do it before.

Furthermore, thank you for providing us with the other app details. We will investigate the issue. Note that we are unable to provide any status updates or other information regarding other developer’s apps on the App Store, and you will not be informed of the results of our investigation.

Please refer to our previous correspondence for details on how to resolve the issues we identified during our review. It would be appropriate to revise your app to ensure it is compliant with our guidelines prior to resubmitting it for review.

Once you have made the appropriate changes to your app, we can continue with our review. We look forward to reviewing your revised and resubmitted app.

Best regards,

App Store Review

**Comment by josefdolezal** [comment]
This seems pretty odd to me, but we have to convince them or they will reject the app. I can create a small write-up by the name of students of CTU for them. Or should we just wait?

**Comment by syky27** [comment]
I honestly do not know what to do, it seems like they made their minds up.

Their responses doesn't make sense.

**Comment by josefdolezal** [comment]
Could you please send our response to them? Something like 'I contacted the students of FIT CTU who are also the maintainers of this app, that it was rejected. This is their reply:

"Hello Apple! Thank you for taking your time to review our app!

We would like to explain you the main intention of this app. At Dejvice, where the campus of CTU (Czech Technical University) is located, there are only few restaurants offering quality and healthy food. We noticed that with low quality and expensive food in restaurants nearby the campus, the students prefer to eat at canteens.

The food at canteens is most of the time unhealthy and the menus usually consists from frozen semi-finished product. In long term, we believe that eating only food like this is healthy risk. With a small group of students and teachers from Faculty of Information Technologies, we decided to change that. We spent enormous amount of time exploring restaurants nearby the campus which offers heathy food. We built a list of these restaurants and would like to introduce them to students.

The last update introduces the new way of exploring restaurants. With map, users are now able to see what restaurant is nearest to their current location. From the restaurant menu, users now can open 3rd party apps to run navigation or check restaurant reviews. This features were created on demand of users (students) who was unable to locate the restaurant by its name.

We understand that the audience of our app is limited, but we believe that the benefit for out users is huge.

We, students and teachers of FIT CTU invested a lot of our spare time building this app. We had to explore the restaurants, we had to build our own backend service which collects the menus, we made this app. The app itself is developed and maintained by students and teachers and there is no business or market intention behind it.

We asked AJTY, s.r.o. for their support. They agreed to help us and offered to release this app under their brand - which we are thankful for.

By the name of students, I would like to ask you to reconsider the app rejection,
Josef Dolezal, student of FIT CTU, LunchGuy contributor."
'

**Comment by syky27** [comment]
Dear AJTY, s.r.o.,
The following app has been approved and the app status has changed to Ready for Sale:

App Name: Obědář 
App Version Number: 1.0.6
App Type: iOS
App SKU: 1464365979
App Apple ID:1118474335
If your contracts are not in effect at this time, your app status will be Pending Contract. You may track the progress of your contracts in the Agreements, Tax, and Banking module in iTunes Connect.

To make changes to this app, sign in to iTunes Connect and open the Manage Your Applications module.

It can take up to 24 hours before your app is available on the App Store. This delay is dependent on any app availability issues.

Before you market your app, read the App Store Marketing and Advertising Guidelines for developers. The guidelines include information on using the App Store badge, best practices to market apps on the App Store, and details on the use of Apple product images.

If you have any questions regarding your app, use the Contact Us module on iTunes Connect.

Regards,
The App Store team

**Comment by rosa130892** [comment]
Hello good afternoon

I also have the same problem I tried to upload my application and I have been rejected 4 times.

De Apple
Guideline 4.2.2 - Design - Minimum Functionality


Hello,

Thank you for the resubmission. 

However, we still noticed that your app only includes links, images, or content aggregated from the Internet with limited or no native iOS functionality. We understand that this content may be curated from the web specifically for your users, but since it does not sufficiently differ from a mobile web browsing experience, it is not appropriate for the App Store.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Minimum Functionality section of the App Store Review Guidelines.
- Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program. 
- Once your app is fully compliant, resubmit your app for review.

If you believe your app is compliant with the App Store Review Guidelines, you may submit an appeal. Alternatively, you may provide additional details about your app by replying directly to this message.


The application has:

Shows content depending on your location otherwise shows national content.
Push notifications
Button to add to my favorites.
Menu where it shows a list of my favorites.
It also has login and user registration.

**Comment by Jignesh1805** [comment]
How to resolved this error rejected by apple
Guideline 4.2.2 - Design - Minimum Functionality

**Comment by syky27** [comment]
@Jignesh1805 add functionality, just like Apple says....

**Comment by Jignesh1805** [comment]
hello sir 
I am already add functionality like push notification , share .
Now which type of add functionality ? please explain me ....

**Comment by syky27** [comment]
You need to discuss this with Apple. 

I cannot help you with this.

**Comment by Jignesh1805** [comment]
ok thank you sir

**Comment by eramudeep** [comment]
From Apple
4. 2 Design: Minimum Functionality
Guideline 4.2.2 - Design - Minimum Functionality


We noticed that your app only includes links, images, or content aggregated from the Internet with limited or no native iOS functionality. Although this content may be curated from the web specifically for your users, since it does not sufficiently differ from a mobile web browsing experience, it is not appropriate for the App Store.

Next Steps

We encourage you to review your app concept and work towards creating an app that offers customers an engaging and lasting experience that also meets the App Store’s high expectations for quality and functionality.

Apple Developer includes a variety of design and development resources. Download iOS templates from Apple UI Design Resources, learn more about crafting intuitive, well-designed apps with the Design Video collection, and review the iOS Human Interface Guidelines for best practices to follow when designing apps for the App Store.
